### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PacketPlayOutWorldParticles

### ISSUE THREAD

**Issue by nuriofernandez** [Jackalantern29/ExplosionRegen#1]
```java
[02:04:06 INFO]: [ExplosionRegen] Enabling ExplosionRegen v3.0.4
[02:04:07 INFO]: [ExplosionRegen] Registered Explosion Settings for 'default' using 'default' block settings.
[02:04:07 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.PacketPlayOutWorldParticles
[02:04:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[02:04:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[02:04:07 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[02:04:07 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[02:04:07 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[02:04:07 WARN]:        at explosionregen-3.0.4.jar//com.jackalantern29.explosionregen.BukkitMethods.<clinit>(BukkitMethods.java:58)
[02:04:07 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[02:04:07 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[02:04:07 WARN]:        at explosionregen-3.0.4.jar//com.jackalantern29.explosionregen.api.ExplosionRegenSettings.setup(ExplosionRegenSettings.java:110)
[02:04:07 WARN]:        at explosionregen-3.0.4.jar//com.jackalantern29.explosionregen.api.ExplosionRegenSettings.<init>(ExplosionRegenSettings.java:36)
[02:04:07 WARN]:        at explosionregen-3.0.4.jar//com.jackalantern29.explosionregen.ExplosionRegen.onEnable(ExplosionRegen.java:26)
[02:04:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:04:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:04:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:04:07 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529)
[02:04:07 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443)
[02:04:07 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[02:04:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[02:04:07 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[02:04:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:04:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[02:04:07 ERROR]: Error occurred while enabling ExplosionRegen v3.0.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at com.jackalantern29.explosionregen.BukkitMethods.getClass(BukkitMethods.java:116) ~[explosionregen-3.0.4.jar:?]
        at com.jackalantern29.explosionregen.ExplosionRegen.onEnable(ExplosionRegen.java:38) ~[explosionregen-3.0.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-160]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-160]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-160]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Paper-160]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-160]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-160]

        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-160]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot read the array length because the return value of "com.jackalantern29.explosionregen.BukkitMethods.getParticles()" is null
        at com.jackalantern29.explosionregen.api.ExplosionParticle.<clinit>(ExplosionParticle.java:11) ~[explosionregen-3.0.4.jar:?]
        ... 14 more
[02:04:07 INFO]: [ExplosionRegen] Disabling ExplosionRegen v3.0.4
```

**Comment by nuriofernandez** [comment]
The [ByteZ1337/ParticleLib](https://github.com/ByteZ1337/ParticleLib) plugin library, has these NMS resolve conditions for version further than 17:

https://github.com/ByteZ1337/ParticleLib/blob/442c79b95529217098ba9ec6fe4a2422fd259dea/src/main/java/xyz/xenondevs/particle/ParticleConstants.java#L244-L277

So, in the 1.17 this packet package seems to have been updated to `.network.protocol.game.PacketPlayOutWorldParticles`.
